package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type SettingSpec struct {
	Key         string
	Default     string
	Description string
	ValueHint   string
	Validator   func(string) error
}

var settingSpecs = []SettingSpec{
	{
		Key:         "MEMSH_AUTOSUGGEST",
		Default:     "1",
		Description: "Enable automatic suggestions while typing",
		ValueHint:   "0|1",
		Validator:   validateBoolSetting,
	},
	{
		Key:         "MEMSH_AUTOSUGGEST_MIN_CHARS",
		Default:     "2",
		Description: "Minimum typed characters before autosuggest starts",
		ValueHint:   "integer >= 1",
		Validator: func(value string) error {
			return validateMinIntSetting(value, 1)
		},
	},
	{
		Key:         "MEMSH_MAX_SUGGESTIONS",
		Default:     "5",
		Description: "Maximum suggestions returned by search and shell flows",
		ValueHint:   "integer >= 1",
		Validator: func(value string) error {
			return validateMinIntSetting(value, 1)
		},
	},
	{
		Key:         "MEMSH_UI_WIDTH",
		Default:     "100",
		Description: "Preferred picker width in terminal columns",
		ValueHint:   "integer >= 60",
		Validator: func(value string) error {
			return validateMinIntSetting(value, 60)
		},
	},
	{
		Key:         "MEMSH_UI_MAX_ITEMS",
		Default:     "10",
		Description: "Maximum visible commands in the picker",
		ValueHint:   "integer >= 3",
		Validator: func(value string) error {
			return validateMinIntSetting(value, 3)
		},
	},
}

func SupportedSettings() []SettingSpec {
	copySpecs := make([]SettingSpec, len(settingSpecs))
	copy(copySpecs, settingSpecs)
	return copySpecs
}

func LookupSetting(key string) (SettingSpec, bool) {
	for _, spec := range settingSpecs {
		if spec.Key == key {
			return spec, true
		}
	}
	return SettingSpec{}, false
}

func DefaultSettings() map[string]string {
	settings := map[string]string{}
	for _, spec := range settingSpecs {
		settings[spec.Key] = spec.Default
	}
	return settings
}

func ReadSettingsFile(path string) (map[string]string, error) {
	settings := map[string]string{}
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return settings, nil
		}
		return nil, fmt.Errorf("read settings file: %w", err)
	}

	for _, rawLine := range strings.Split(string(content), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		line = strings.TrimPrefix(line, "export ")
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.Trim(strings.TrimSpace(parts[1]), "\"")
		if _, ok := LookupSetting(key); ok {
			settings[key] = value
		}
	}

	return settings, nil
}

func WriteSettingsFile(path string, settings map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	keys := make([]string, 0, len(settings))
	for key := range settings {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	lines := []string{"# Generated by memsh settings", "# Reload your shell after changes: source ~/.zshrc", ""}
	for _, key := range keys {
		lines = append(lines, fmt.Sprintf("export %s=%q", key, settings[key]))
	}
	lines = append(lines, "")

	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644); err != nil {
		return fmt.Errorf("write settings file: %w", err)
	}

	return nil
}

func ValidateSetting(key string, value string) error {
	spec, ok := LookupSetting(key)
	if !ok {
		return fmt.Errorf("unsupported setting %q", key)
	}

	if spec.Validator != nil {
		if err := spec.Validator(strings.TrimSpace(value)); err != nil {
			return fmt.Errorf("invalid %s: %w", key, err)
		}
	}

	return nil
}

func validateBoolSetting(value string) error {
	if value != "0" && value != "1" {
		return fmt.Errorf("expected 0 or 1")
	}
	return nil
}

func validateMinIntSetting(value string, minimum int) error {
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("expected integer")
	}
	if parsed < minimum {
		return fmt.Errorf("expected value >= %d", minimum)
	}
	return nil
}
